# Generated by Django 4.1.7 on 2023-04-17 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0002_remove_customers_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='image',
            field=models.CharField(default='', max_length=255),
        ),
    ]
