# Generated by Django 4.1.7 on 2023-04-24 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0005_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post_property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(max_length=50)),
                ('sub_property_type', models.CharField(max_length=150)),
                ('property_image', models.CharField(default='', max_length=255)),
                ('area', models.CharField(max_length=150)),
                ('address', models.TextField()),
                ('contact', models.BigIntegerField()),
                ('Customers', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myadmin.customers')),
            ],
            options={
                'db_table': 'post_property',
            },
        ),
    ]
