# Generated by Django 4.1.7 on 2023-04-25 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0007_post_property_property_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post_property',
        ),
    ]
