# Generated by Django 4.1.7 on 2023-04-26 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0014_add_more_images'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Add_more_images',
        ),
    ]
