# Generated by Django 4.1.7 on 2023-04-28 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0021_remove_post_property_area_remove_post_property_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='city',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.RemoveField(
            model_name='customers',
            name='user',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='customers',
        ),
        migrations.DeleteModel(
            name='Area',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Customers',
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
