# Generated by Django 4.1.7 on 2023-04-28 09:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myadmin', '0022_remove_area_city_delete_contact_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'area',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citys', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'city',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('phone', models.BigIntegerField()),
                ('email', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
            ],
            options={
                'db_table': 'contact',
            },
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('contact', models.BigIntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('image', models.CharField(default='', max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'customers',
            },
        ),
        migrations.CreateModel(
            name='Post_property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_for', models.CharField(max_length=50)),
                ('property_type', models.CharField(max_length=30)),
                ('sub_property_type', models.CharField(max_length=150)),
                ('property_name', models.CharField(max_length=150)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('rooms', models.CharField(max_length=50)),
                ('property_age', models.CharField(max_length=30)),
                ('types', models.CharField(max_length=30)),
                ('facility', models.CharField(max_length=150)),
                ('maintenance', models.CharField(max_length=50)),
                ('property_description', models.TextField()),
                ('address', models.TextField()),
                ('contact', models.BigIntegerField()),
                ('property_image', models.CharField(max_length=255)),
                ('area', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myadmin.area')),
                ('city', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myadmin.city')),
                ('customers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.customers')),
            ],
            options={
                'db_table': 'post_property',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(max_length=50)),
                ('comment', models.TextField()),
                ('date', models.DateField(auto_now=True)),
                ('customers', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myadmin.customers')),
            ],
            options={
                'db_table': 'feedback',
            },
        ),
        migrations.AddField(
            model_name='area',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.city'),
        ),
        migrations.CreateModel(
            name='Add_more_images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=255)),
                ('post_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.post_property')),
            ],
            options={
                'db_table': 'add_more_images',
            },
        ),
    ]
