# Generated by Django 4.1.7 on 2023-04-28 17:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0024_post_property_sq_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buy_property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('cur_date', models.DateField(default=datetime.date.today)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to='myadmin.customers')),
                ('post_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.post_property')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to='myadmin.customers')),
            ],
            options={
                'db_table': 'buy_property',
            },
        ),
    ]
