# Generated by Django 4.1.7 on 2023-04-24 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0006_post_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_property',
            name='property_description',
            field=models.TextField(default=''),
        ),
    ]
