# Generated by Django 4.1.7 on 2023-04-25 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0009_post_property'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post_property',
        ),
    ]
