# Generated by Django 4.1.7 on 2023-04-25 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0010_delete_post_property'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post_property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_for', models.CharField(max_length=50)),
                ('property_type', models.CharField(max_length=30)),
                ('sub_property_type', models.CharField(max_length=150)),
                ('property_name', models.CharField(max_length=150)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('rooms', models.CharField(max_length=50)),
                ('property_age', models.CharField(max_length=30)),
                ('types', models.CharField(max_length=30)),
                ('facility', models.CharField(max_length=150)),
                ('maintenance', models.CharField(max_length=50)),
                ('area', models.CharField(max_length=150)),
                ('property_description', models.TextField()),
                ('address', models.TextField()),
                ('contact', models.BigIntegerField()),
                ('property_image', models.CharField(max_length=255)),
                ('Customers', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myadmin.customers')),
            ],
            options={
                'db_table': 'post_property',
            },
        ),
    ]
