# Generated by Django 4.1.7 on 2023-04-25 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0011_post_property'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post_property',
            old_name='Customers',
            new_name='customers',
        ),
    ]
